### ISSUE TITLE
imperfect balancing and only for some time

### ISSUE THREAD

**Issue by BertLindeman** [laurensvalk/segway#14]
As suggested by @laurensvalk in #11 

## Hardware:
Running EV3 brick with LEGO reloadable battery and HiTechnic Gyro sensor

## Software:
**System info (from `ev3dev-sysinfo`)**
```
Image file:         ev3dev-stretch-ev3-generic-2017-10-24
Kernel version:     4.9.58-ev3dev-1.6.0-ev3
Brickman:           0.10.0
ev3devKit:          0.5.2
Board:              board0
BOARD_INFO_HW_REV=7
BOARD_INFO_MODEL=LEGO MINDSTORMS EV3
BOARD_INFO_ROM_REV=6
BOARD_INFO_SERIAL_NUM=0016535166E2
BOARD_INFO_TYPE=main
```

Using segway.py and parameters.py at a [previous commit](https://github.com/laurensvalk/segway/commit/6c278d4e48b6acf48363f627ae3870aec4d4c72e#diff-647d7290558ac07e32a3e49b10ba02c4)

## Symptoms:
The robot *does* balance but only for some seconds.

## Environment:
Robot runs on carpet so it does not fall too hard ;-)

## Progress:
Will test later on harder floor

**Comment by laurensvalk** [comment]
> Robot runs on carpet so it does not fall too hard, Will test later on harder floor

Ah - good point. I should probably point out in the code that the provided values are for hard surfaces such as a wooden desk or tile floor.

**Comment by BertLindeman** [comment]
Will add though that the EV3-G project did not have this problem in the same soft floor. 
But that configuration does not run debian services in the background.

Not sure if this has an impact here: running the segway.py via ssh-wifi connection.

**Comment by laurensvalk** [comment]
Ok thanks for that additional information. 

WiFi can be a factor. You could boot the EV3 without the WiFi dongle and try running it from brickman to see if there is much difference.

**Comment by BertLindeman** [comment]
Done hard / soft floor and WIFI/NoWIFI tests. WIFI *does* have an impact and soft floor does too. 
To see for yourself I uploaded a [youtube movie](https://youtu.be/AFMb7cS8QOs) showing the four situations.

UPDATE: youtube video uploaded

**Comment by laurensvalk** [comment]
:tada: :tada: :tada: :tada: :tada:

Thanks for sharing! For now I am going to call that an absolute success (the case without WiFi on a rigid floor), and you are welcome to join us over at [this issue](https://github.com/laurensvalk/segway/issues/10) :-)

**Comment by BertLindeman** [comment]
Close this one, if there come more recommendations they will come in issue #10 

Recommendations found in here: 
- use a hard surface to run the robot on
- turn WIFI OFF
