### ISSUE TITLE
[VEX IQ] modkit help

### ISSUE THREAD

**Issue by isamol** [laurensvalk/segway#2]
the program is great, but at school i am not allowed to use ROBOTC. i am not very good at translating the code, but if you know a way than can you please post it. help me

**Comment by laurensvalk** [comment]
Thanks for your message. Unfortunately, I don't have version for Modkit at this time.

I think it can be done, but it will be a bit cumbersome as the Modkit program would become quite large. It appears that Modkit is also missing some features such as arrays. (Though it is possible to work around this for this particular program.)

**Comment by laurensvalk** [comment]
RobotC is now free of charge for VEX IQ users, which should resolve the barrier for most users. I'll be closing this issue.
