### ISSUE TITLE
Issue testing the segway.py file

### ISSUE THREAD

**Issue by ghost** [laurensvalk/segway#7]
Hi,

i'm new to ev3 gyroboy - mindstorm and i was trying to use the code in this link:

https://github.com/laurensvalk/segway/tree/master/ev3/ev3dev/python

to test it and see how it works. but i keep getting multiple errors:

1- permission denied = changed the permission to 777
2- text file busy = ??

i also created the file makelinks.sh but still can't test the code.

Thanks

**Comment by laurensvalk** [comment]
First, transfer "makelinks.sh" and "segway.py" to your EV3, and put them in the same directory.
To turn them into executable scripts, run:
```
chmod +x makelinks.sh
chmod +x segway.py
```
Now you can run the program: 
```
./segway.py
```
hold segway up right with its resting wheels on the ground and wait for the program to start.

**Comment by ghost** [comment]
i'm still getting this error:

-bash: ./segway.py: /usr/bin/env: bad interpreter: Text file busy

**Comment by andoors2011** [comment]
i'm still getting this error:

-bash: ./segway.py: /usr/bin/env: bad interpreter: Text file busy

**Comment by laurensvalk** [comment]
Can you retry it after you restart the brick?

Also, can you run only 

```
./makelinks.sh
ls -al
```
and give the output?

**Comment by ghost** [comment]
i managed to get it to run and work properly 
using sudo ./segway.py probably it needed admin access to force it to work.

Thanks

**Comment by laurensvalk** [comment]
It shouldn't require that, though --- perhaps because something else was also accessing the file, from your previous attempts. Perhaps after a restart it shouldn't need that.

**Comment by andoors2011** [comment]
Thanks a lot for your help.

You mentioned on the main page that a tutorial that explains the code is going to be released, are you planning to release a step by step explanation ?

If you can please, can you tell me what can I add to my original code to get it to work? What exactly was I missing ? the information in the internet says that the duty cycle is the only thing that matters when getting values from the PID controller, I’m sorry but I still don’t understand the reason it’s not working.

One more inquiry, what’s Segway-line.py that’s listed in the directory ? what does it do?

I’m really sorry, I have so many questions as I’m fresh starting to learn this thing.

Thanks again,

Andrew Mikaiel
