### ISSUE TITLE
Where's the docs?

### ISSUE THREAD

**Issue by yaniv4345** [laurensvalk/segway#9]
Hi I'm looking for the docs for the ev3 segway.py code.
Where can i find it?

**Comment by laurensvalk** [comment]
I'm afraid the comments are all there are at this point. There is also abundant literature on the control theory side of things. The theory and application is similar to the inverted pendulum chart.

Is there anything in particular you are interested in?

**Comment by yaniv4345** [comment]
There where a few places in the older version that referred the the documentation.
This is not relevant any more as we already finished our project (it was for a school project).
We added some movement function to the code with a dedicated web site for remote control.
Thank you.
